### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by NotAShelf** [privatevoid-net/nix-super#11]
**Describe the bug**

The latest commit fails to build due to failed tests.
Logs: https://p.frzn.dev/wci/

**Steps To Reproduce**

1. Pin nix-super input to the latest commit (or simply don't pin it)
2. Add the following to `nixpkgs.overlays`
```nix 
(self: super: {
     nixSuper = inputs.nix-super.packages.x86_64-linux.default;
 })
```
3. Set `nix.package` to `pkgs.nixSuper`
4. Rebuild the system

**Expected behavior**

Nix should compile as usual on a rebuild.

**Comment by max-privatevoid** [comment]
Thanks for the report. Looks like this was an upstream build failure. Fixed via https://github.com/privatevoid-net/nix-super/commit/16e733360f186555acc490c7f5173711b8dd6785
